version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: shopper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./pg_hba.conf:/var/lib/foo/pg_hba.conf
    command: ["postgres", "-c", "hba_file=/var/lib/foo/pg_hba.conf"]

  backend:
    build:
      context: ./shopper-api
    container_name: backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: shopper
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./shopper-api:/app
    command: ["sh", "-c", "npm run migration:run && npm run start"]

volumes:
  db_data:
